# Generated by Django 3.2.4 on 2021-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_1', models.CharField(max_length=300)),
                ('box_2', models.CharField(max_length=300)),
                ('box_3', models.CharField(max_length=300)),
                ('box_4', models.CharField(max_length=300)),
            ],
        ),
    ]
